// <auto-generated />
using CollageApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollageApi.Migrations
{
    [DbContext(typeof(CollageContext))]
    [Migration("20260922231301_addeddataIntoStudentForStartupPropject")]
    partial class addeddataIntoStudentForStartupPropject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollageApi.Data.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = 24,
                            Email = "iqra@gmail.com",
                            Name = "iqra"
                        },
                        new
                        {
                            ID = 2,
                            Age = 25,
                            Email = "hira@gmail.com",
                            Name = "hira"
                        },
                        new
                        {
                            ID = 3,
                            Age = 20,
                            Email = "hani@gmail.com",
                            Name = "hani"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
